give_dose:
  fields:
    child_id:
      required: true
      selector:
        text:
    medicine:
      required: true
      selector:
        select:
          options:
            - paracetamol
            - ibuprofen
    dose_mg:
      required: false
      selector:
        number:
          min: 0
          max: 5000
          unit_of_measurement: mg
clear_history:
  fields:
    child_id:
      required: false
      selector:
        text:
    medicine:
      required: false
      selector:
        select:
          options:
            - paracetamol
            - ibuprofen
